name: Web Page Test
on: [push]
jobs:
  Jest:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: "npx serve -l 127.0.0.1:5000 & echo 'Waiting for web server to bring up...'; sleep 15; curl 'http://127.0.0.1:5000/index.html'; cd tests; npm install --save-dev jest puppeteer jest-puppeteer; npm test"