name: Web Page Test
on: [push]
jobs:
  Jest:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i jest puppeteer jest-puppeteer
    - run: "cd tests; jest"