name: Web Page Test
on: [push]
jobs:
  Jest:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: "cd tests; npm install --save-dev jest puppeteer jest-puppeteer; npm test"